export const symbolMap = {
  'f': '/assets/tiles/3.svg',
  'h': '/assets/tiles/4.svg',
  'i': '/assets/tiles/5.svg',
  'j': '/assets/tiles/6.svg',
  '1': '/assets/tiles/18.svg',
  '2': '/assets/tiles/19.svg',
  '3': '/assets/tiles/20.svg',
  '4': '/assets/tiles/22.svg',
  '5': '/assets/tiles/23.svg',
  '6': '/assets/tiles/24.svg',
  'r': '/assets/tiles/41.svg',
  's': '/assets/tiles/42.svg',
  'c': '/assets/tiles/27.svg',
  'k': '/assets/tiles/43.svg',
  'g': '/assets/tiles/9.svg',
  'C': '/assets/tiles/14.svg',
  '0': '/assets/tiles/16.svg',
  '_': '/assets/tiles/1.svg',
  't': '/assets/tiles/26.svg',
  'b': '/assets/tiles/39.svg',
  'a': '/assets/tiles/37.svg',
  'v': '/assets/tiles/7.svg',
  'm': '/assets/tiles/8.svg',
  '!': '/assets/tiles/29.svg',
  '@': '/assets/tiles/30.svg',
  '#': '/assets/tiles/31.svg',
  '$': '/assets/tiles/32.svg',
  '%': '/assets/tiles/33.svg',
  '^': '/assets/tiles/34.svg',
  '&': '/assets/tiles/36.svg',
  '*': '/assets/tiles/17.svg',
  'd': '/assets/tiles/2.svg',
};

export const tiles = [
  `hhh1rsr2r3rkhh`,
  `hhhvhhhvhhhvhh`,
  `r0rchhhdr4rmhh`,
  `hhhghhhvhhhhhh`,
  `hhhdrCr*hh$@#h`,
  `h__v_hhh$@^t!h`,
  `__adamrk%rrb!h`,
  `_aavaa_v!___!h`,
  `_aa5rsr6&@@@^h`,
  `______________`,
].join('');
